project:
  type: website
  output-dir: docs

  
website:
  title: "STAT-462 Lab Book"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Labs"
        contents:
          - in_S462_Lab0Index.qmd
          - in_S462_Lab1.qmd
          - in_S462_Lab2.qmd
          - in_S462_Lab3.qmd
          - in_S462_Lab4.qmd
          - in_S462_Lab5.qmd
      - section: "Project"
        contents:
          - in_S462_Project00Index.qmd
          - in_S462_Project01MakingGroups.qmd
          - in_S462_Project02Setup.qmd
          - in_S462_Project03InitialEDA.qmd
          - in_S462_Project04Final.qmd
          - in_S462_Project04FinalUPDATED.qmd
      - section: "Tutorials"
        contents:
          - in_S462_Tutorial01WhatisR.qmd
          - in_S462_Tutorial02BeforeEachLab.qmd
          - in_S462_Tutorial03RBasics.qmd
          - in_S462_Tutorial04AdvancedMarkdown.qmd
          - in_S462_Tutorial05LoadingData.qmd
          - in_S462_Tutorial06Wrangling.qmd
          - in_S462_Tutorial07Distributions.qmd
          - in_S462_Tutorial08Plots.qmd
          - in_S462_Tutorial09Correlation.qmd          
          - in_S462_Tutorial10Regression.qmd          
format:
  html:
    css: styles.css
    toc: true
    theme:
       light: flatly
       dark: darkly
    fontsize: 0.95em
    linestretch: 1.7
