project:
  type: website
  output-dir: docs
  
website:
  title: "STAT-462 Lab Book"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorials"
        contents:
          - in_S462_Tutorial1WhatisR.qmd
          - in_S462_Tutorial2BeforeEachLab.qmd
          - in_S462_Tutorial3RBasics.qmd
          - in_S462_Tutorial4AdvancedMarkdown.qmd
      - section: "Labs"
        contents:
          - in_S462_Lab0Index.qmd
          - in_S462_Lab1.qmd
          - in_S462_Lab2.qmd
      - section: "Project"
        contents:
          - in_S462_Project0Index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true