project:
  type: website
  output-dir: docs
  
website:
  title: "STAT-462 Lab Book"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Labs"
        contents:
          - in_S462_Lab0Index.qmd
          - in_S462_Lab1.qmd
          - in_S462_Lab2.qmd
      - section: "Project"
        contents:
          - in_S462_Project0Index.qmd
          - in_S462_Project1MakingGroups.qmd
          - in_S462_Project2Setup.qmd
          - in_S462_Project3InitialEDA.qmd
      - section: "Tutorials"
        contents:
          - in_S462_Tutorial1WhatisR.qmd
          - in_S462_Tutorial2BeforeEachLab.qmd
          - in_S462_Tutorial3RBasics.qmd
          - in_S462_Tutorial4AdvancedMarkdown.qmd
          - in_S462_Tutorial5LoadingData.qmd
          - in_S462_Tutorial6Wrangling.qmd
          - in_S462_Tutorial7Distributions.qmd
          - in_S462_Tutorial8Plots.qmd
          - in_S462_Tutorial9Correlation.qmd          
format:
  html:
    css: styles.css
    toc: true
    theme:
       light: flatly
       dark: darkly
    fontsize: 0.95em
    linestretch: 1.7